# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on: [pull_request, workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.5
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: afteedb_test
          POSTGRES_USER: i04npdb
          POSTGRES_PASSWORD: i04npdb
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    strategy:
      matrix:
        ruby-version: ['2.5.8']

    steps:
    - uses: actions/checkout@v3

    - name: Set up default schema
      run: |
        PGPASSWORD=i04npdb psql -h localhost -U i04npdb -d afteedb_test -c "CREATE SCHEMA IF NOT EXISTS daisy;"
        PGPASSWORD=i04npdb psql -h localhost -U i04npdb -d afteedb_test -c "ALTER ROLE i04npdb SET search_path = daisy, public;"
        PGPASSWORD=i04npdb psql -h localhost -U i04npdb -d afteedb_test -c "SELECT schema_name FROM information_schema.schemata;"
        # Add any additional SQL commands you need here
    
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run db migrate
      run: |
        bundle exec rake db:migrate:reset RAILS_ENV=test

    - name: check up default schema
      run: |
        PGPASSWORD=i04npdb psql -h localhost -U i04npdb -d afteedb_test -c "SELECT schema_name FROM information_schema.schemata;"
        PGPASSWORD=i04npdb psql -h localhost -U i04npdb -d afteedb_test -c "SELECT * from daisy.candidates;"
        
    - name: Run tests
      run: |
        bundle exec rake

    - name: check up default schema
      run: |
        PGPASSWORD=i04npdb psql -h localhost -U i04npdb -d afteedb_test -c "SELECT schema_name FROM information_schema.schemata;"
        PGPASSWORD=i04npdb psql -h localhost -U i04npdb -d afteedb_test -c "SELECT * from candidates;"
        PGPASSWORD=i04npdb psql -h localhost -U i04npdb -d afteedb_test -c "SELECT * from daisy.candidates;"
        PGPASSWORD=i04npdb psql -h localhost -U i04npdb -d afteedb_test -c "SELECT * from candidates;"
        # Add any additional SQL commands you need here
